joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: /joy_vel
      deadman_buttons: [5]
      axis_mappings:
        twist-linear-x:
          axis: 1
          scale: 2.0
          offset: 0.0
        twist-linear-y:
          axis: 3
          scale: 2.0
          offset: 0.0
        twist-angular-z:
          axis: 0
          scale: 5.0
          offset: 0.0
