ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    publish_tf: true

    # Frames
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint_ekf     
    world_frame: odom              # EKF local (contínuo) para controle

    sensor_timeout: 0.2
    print_diagnostics: true
    reset_on_time_jump: true

    # ---------------- IMU ----------------
    # Ajuste o tópico!
    imu0: /imu/data
    # x y z | roll pitch yaw | vx vy vz | vroll vpitch vyaw | ax ay az
    imu0_config: [false, false, false,
                  false, false,  true,
                  false, false, false,
                  false, false,  true,
                  true,  true,  false]
    imu0_differential: false
    imu0_pose_use_child_frame: false
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 10

    # --------------- ODOM --------------- 
    # Use a odometria do seu controlador mecanum (normalmente nav_msgs/Odometry)
    # Ajuste o tópico! Ex.: /mecanum_controller/odometry
    odom0: /mecanum_controller/odometry

    # Para mecanum, funda apenas velocidades: vx, vy e vyaw (wz)
    # x y z | roll pitch yaw | vx  vy   vz | vroll vpitch vyaw | ax ay az
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_pose_use_child_frame: false
    odom0_queue_size: 10

    # Ruído de processo (ponto de partida razoável)
  process_noise_covariance: [0.05, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.05, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.06,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.03, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.03, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.03,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.02, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.02, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.04,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.01, 0.0, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.01, 0.0,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.02,  0.0, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.01, 0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.01, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.015]

    # Covariância inicial (rápida convergência em 2D; z/roll/pitch menos confiáveis)
  initial_estimate_covariance: [1e-3, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 1e-3, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 1e-1,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   1e-1, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 1e-1, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 1e-3,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   1e-2, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 1e-2, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 1e-1,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   1e-2, 0.0, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 1e-2, 0.0,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 1e-2,  0.0, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   1e-1, 0.0, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 1e-1, 0.0,
                  0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 0.0,   0.0, 0.0, 1e-1]
